apiVersion: v1
kind: Service
metadata:
  name: clusterpedia-apiserver
  namespace: karmada-system
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: clusterpedia-apiserver
