apiVersion: v1
kind: Service
metadata:
  name: clusterpedia-apiserver
  namespace: karmada-system
spec:
  externalName: clusterpedia-apiserver.karmada-system.svc.cluster.local
  internalTrafficPolicy: Cluster
  sessionAffinity: None
  type: ExternalName
